
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 25 21:37:28 PET 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 26;
  public static final int Palabra_clave = 10;
  public static final int Coma = 9;
  public static final int Llave_c = 32;
  public static final int Op_booleano = 12;
  public static final int Llave_a = 31;
  public static final int If = 16;
  public static final int Else = 17;
  public static final int Variable = 7;
  public static final int Corchete_c = 34;
  public static final int Corchete_a = 33;
  public static final int Punto = 5;
  public static final int While = 19;
  public static final int Division = 24;
  public static final int Int = 14;
  public static final int Cadena = 15;
  public static final int Parentesis_c = 30;
  public static final int Parentesis_a = 29;
  public static final int For = 20;
  public static final int P_coma = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 27;
  public static final int ERROR = 37;
  public static final int Do = 18;
  public static final int Op_logico = 25;
  public static final int Var_anonima = 13;
  public static final int Resta = 22;
  public static final int Atom = 6;
  public static final int Multiplicacion = 23;
  public static final int Op_incremento = 28;
  public static final int Numero = 8;
  public static final int Suma = 21;
  public static final int Main = 35;
  public static final int Igual = 11;
  public static final int Comilla = 4;
  public static final int Comillas = 3;
}

